### ISSUE TITLE
well, this is beyond me

### ISSUE THREAD

**Issue by DBright682** [NotCookey/PyFileDownloader#1]
TypeError: 'NoneType' object is not subscriptable
![image](https://user-images.githubusercontent.com/116032065/196312100-708d6a06-2449-4413-8980-1b45496bcf91.png)

**Comment by NotCookey** [comment]
> TypeError: 'NoneType' object is not subscriptable ![image](https://user-images.githubusercontent.com/116032065/196312100-708d6a06-2449-4413-8980-1b45496bcf91.png)
Well seems like some headers don't carry the filename in it. I will put a check to set it to a random string if it's None.
